Add NVIDIA as a Provider and expose it to Goose
block/goose pull request #132
Opened 2024-10-09 04:12 UTC by praateekmahajan

Creates a provider in `exchange`. 
In goose, adds a config for the NVIDIA provider (using `llama-3.1-405b`) to `default_model_configuration`

2024-10-09 16:41 UTC, adhintz commented on pyproject.toml
> +
Was this an accidental change?

2024-10-09 16:46 UTC, adhintz commented on src/goose/cli/config.py
> +    processor, accelerator = recommended.get(provider, recommended["nvidia"])
I think this line should be reverted. Is there a reason to change the default values to nvidia's values?

Your change on line 105 should work to set the default configuration to nvidia when it detects NVIDIA_API_KEY.

2024-10-09 18:10 UTC, lamchau commented on packages/exchange/src/exchange/providers/nvidia.py
> +    def from_env(cls: Type["NVIDIAProvider"]) -> "NVIDIAProvider":
this works but @elenazherdeva introduced `cls.check_env_vars()` pattern so these can be checked upfront avoiding the need for a `try/except` block 

https://github.com/block-open-source/goose/blob/8276e9b01f1f9ffe17b9388861b52ed96066c3c4/packages/exchange/src/exchange/providers/google.py#L25-L27

2024-10-10 08:50 UTC, michaelneale requested changes
looks great - if can just get that small tweak

2024-10-10 08:50 UTC, michaelneale commented on src/goose/cli/config.py
> +    processor, accelerator = recommended.get(provider, recommended["nvidia"])
```suggestion
    processor, accelerator = recommended.get(provider, ("gpt-4o", "gpt-4o-mini"))
```

2024-10-24 00:57 UTC, michaelneale commented
@praateekmahajan you ok if I take this on and finish it up to get it in?

2024-10-30 03:38 UTC, michaelneale approved these changes

2024-10-30 06:12 UTC, praateekmahajan commented
@michaelneale hey sorry for the late response, I had marked it as draft since it was a POC, and I was trying to get it to work with LLAMA 3.1 but wasn't able to. If you've been able to that's great. And thanks for taking it over, I haven't had the bandwidth to look at this and make it work yet.

2024-10-31 03:10 UTC, michaelneale commented
@praateekmahajan no worries - yes at some point we will iterate a bit on the newer llamas (main thing was tool calling was not great generally yet - but will get better)

2025-02-14 23:56 UTC, closed without merging