What's new in Goose
block/goose pull request #428
Opened 2024-12-06 17:08 UTC by acekyd

This pull request includes a new blog post announcing the release of Goose v1.0. The blog post highlights several new features and improvements in the latest version.

Key highlights of the Goose v1.0 release:

* Transition to Rust: The core of Goose is being rewritten in Rust for a more portable and stable experience.
* Contextual Memory: Goose will now remember previous interactions to better understand ongoing projects.
* Improved Plugin System: The plugin system is updated to support more complex plugins and integrations.
* Headless Mode: Goose can now run in headless mode, useful for server environments.
* New GUI: Goose now includes an electron-based GUI application for easier interaction and project management.

2024-12-10 15:01 UTC, EbonyLouis requested changes

2024-12-10 15:01 UTC, EbonyLouis commented on docs/blog/posts/2024-12-06-previewing-goose-v1.md
> +  meta:
Take it out of the `frontmatter` it didn't work the only "non" disruptive thing that we can do is put it at the bottom of the page. We'll still have that annoying gap but its better than it being at the top and its better than nothing at all

2024-12-10 17:08 UTC, acekyd commented on docs/blog/posts/2024-12-06-previewing-goose-v1.md
> +  meta:
Thanks @EbonyLouis... updated!

2024-12-11 10:36 UTC, angiejones approved these changes

2024-12-11 10:43 UTC, merged