fix: Update cli.md
block/goose pull request #436
Opened 2024-12-09 22:37 UTC by michaelneale

cc @taniashiba

2024-12-09 23:13 UTC, taniashiba requested changes

2024-12-09 23:13 UTC, taniacryptid commented on docs/plugins/cli.md
> +It will run this plan to completion as a one shot task
I like plan! It's pretty standard, and a way to group tasks into a single, one-off execution. I would add either one of these sentences to make it extra clear, if wanted:

- `It will run this plan, or sequence of tasks, to completion as a one shot task.` 
or
- `It will run this plan (sequence of tasks) to completion as a one shot task.` 

People will naturally wonder if the order of tasks matters or what, and adding that additional description helps!

2024-12-09 23:48 UTC, taniashiba approved these changes

2024-12-10 20:34 UTC, EbonyLouis approved these changes

2024-12-10 20:34 UTC, merged